name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write clean signal file
        run: echo 'AzerothLM_Signal = {}' > AzerothLM_Signal.lua

      - uses: BigWigsMods/packager@v2
